# This file was generated by GoReleaser. DO NOT EDIT.
cask "pdfunlock" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args:           ["-dr", "com.apple.quarantine", "{{staged_path}}/pdfunlock"],
          writable_paths: ["pdfunlock"]
    end
  end

  version "1.1.0"

  on_macos do
    on_arm do
      sha256 "2b89ee0e822f75a3c811398f1527d7c07a82290f2f2a88d7a090984e54078fb0"
      url "https://github.com/fadeltd/pdfunlock/releases/download/v#{version}/pdfunlock_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9d6ce1873673a87cde03a05d444ff5ecabb0d5ddcf2e1051cb6e0657dd3bb32a"
      url "https://github.com/fadeltd/pdfunlock/releases/download/v#{version}/pdfunlock_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3c12741b15d5a1c69ca3f37775bb48ed21b564d2228999e669c5438859a94561"
      url "https://github.com/fadeltd/pdfunlock/releases/download/v#{version}/pdfunlock_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6cf64ae68a336dae05acb33c14f7498cf49bc0ba01ad4d9bc5ea1750032d31b2"
      url "https://github.com/fadeltd/pdfunlock/releases/download/v#{version}/pdfunlock_Linux_x86_64.tar.gz"
    end
  end

  name "pdfunlock"
  desc "Unlock password-protected PDF files from the command-line"
  homepage "https://fadeltd.github.io/pdfunlock/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pdfunlock"

  # No zap stanza required
end
